# Generated by Django 4.1.4 on 2024-12-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='booklist',
            new_name='book_list',
        ),
        migrations.AlterField(
            model_name='booklist',
            name='month',
            field=models.CharField(max_length=10),
        ),
    ]
